name: Scheduled Workflow

on:
  workflow_dispatch:  # Manual trigger option
  schedule:
    - cron: '0 0 * * 3'  # Runs every Wednesday at midnight

jobs:
  print_time:
    runs-on: ubuntu-latest
    steps:
    - name: Print current time
      run: date
